<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <meta name="robots" content="noindex">
        <style>html {background-color: #fff}</style>
        <link rel="stylesheet" href="../../../style.css">
        <title>src/part1/Registration.java · Part-1-S2 · GitFront</title>
    </head>
    <body>
        <div class="container">
            <div class="location">
                <a href="../../..">Part-1-S2</a> /
                <a href="../../../tree/src/">src</a> /
                <a href="../../../tree/src/part1/">part1</a> /
                <span>Registration.java</span>
            </div>

            <div class="blob-view">
                <div class="header">
                    <div class="header-basename">Registration.java</div>
                    <div class="last">
                        <a class="btn" href="../../../raw/src/part1/Registration.java">Raw</a>
                    </div>
                </div>
                <div class="content ">
                    <pre tabindex="0" class="highlight-chroma"><code><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-kn">package</span> <span class="highlight-nn">part1</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-kn">import</span> <span class="highlight-nn">javax.swing.JOptionPane</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">/**
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm"> *Student Number:
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm"> * Full Name: 
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm"> * Assignment: 
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm"> * 
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm"> */</span>
</span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-kd">public</span> <span class="highlight-kd">class</span> <span class="highlight-nc">Registration</span> <span class="highlight-kd">extends</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JFrame</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1">//     JTextField txtUsername, txtFirstname, txtLastname;
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span><span class="highlight-c1">//    JPasswordField txtPassword;
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>    <span class="highlight-n">String</span> <span class="highlight-n">storedUsername</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-n">String</span> <span class="highlight-n">storedPassword</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-cm">/**
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     * Creates new form Registration
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-nf">Registration</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">initComponents</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">         <span class="highlight-n">setTitle</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Registration&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">setSize</span><span class="highlight-o">(</span><span class="highlight-n">500</span><span class="highlight-o">,</span> <span class="highlight-n">400</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">setLocationRelativeTo</span><span class="highlight-o">(</span><span class="highlight-kc">null</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">setDefaultCloseOperation</span><span class="highlight-o">(</span><span class="highlight-n">EXIT_ON_CLOSE</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    
</span></span><span class="highlight-line"><span class="highlight-cl">    
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-cm">/**
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     * This method is called from within the constructor to initialize the form.
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     * WARNING: Do NOT modify this code. The content of this method is always
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     * regenerated by the Form Editor.
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-nd">@SuppressWarnings</span><span class="highlight-o">(</span><span class="highlight-s">&#34;unchecked&#34;</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-c1">// &lt;editor-fold defaultstate=&#34;collapsed&#34; desc=&#34;Generated Code&#34;&gt;//GEN-BEGIN:initComponents
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>    <span class="highlight-kd">private</span> <span class="highlight-kt">void</span> <span class="highlight-nf">initComponents</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel1</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel2</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel3</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel4</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">txtUsername</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">txtFirstname</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">txtLastname</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">txtPassword</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JPasswordField</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">btnSubmit</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JButton</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">setDefaultCloseOperation</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">WindowConstants</span><span class="highlight-o">.</span><span class="highlight-na">EXIT_ON_CLOSE</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel1</span><span class="highlight-o">.</span><span class="highlight-na">setText</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Username&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel2</span><span class="highlight-o">.</span><span class="highlight-na">setText</span><span class="highlight-o">(</span><span class="highlight-s">&#34;First Name&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel3</span><span class="highlight-o">.</span><span class="highlight-na">setText</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Last Name&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">jLabel4</span><span class="highlight-o">.</span><span class="highlight-na">setText</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Password&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">btnSubmit</span><span class="highlight-o">.</span><span class="highlight-na">setText</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Register&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">btnSubmit</span><span class="highlight-o">.</span><span class="highlight-na">addActionListener</span><span class="highlight-o">(</span><span class="highlight-k">new</span> <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">awt</span><span class="highlight-o">.</span><span class="highlight-na">event</span><span class="highlight-o">.</span><span class="highlight-na">ActionListener</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-kd">public</span> <span class="highlight-kt">void</span> <span class="highlight-nf">actionPerformed</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">awt</span><span class="highlight-o">.</span><span class="highlight-na">event</span><span class="highlight-o">.</span><span class="highlight-na">ActionEvent</span> <span class="highlight-n">evt</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-n">btnSubmitActionPerformed</span><span class="highlight-o">(</span><span class="highlight-n">evt</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span> <span class="highlight-n">layout</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">(</span><span class="highlight-n">getContentPane</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">getContentPane</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">setLayout</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">setHorizontalGroup</span><span class="highlight-o">(</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createSequentialGroup</span><span class="highlight-o">(</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createSequentialGroup</span><span class="highlight-o">(</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">29</span><span class="highlight-o">,</span> <span class="highlight-n">29</span><span class="highlight-o">,</span> <span class="highlight-n">29</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">,</span> <span class="highlight-kc">false</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel1</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">51</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel2</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">77</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel3</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel4</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">,</span> <span class="highlight-kc">false</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtUsername</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">182</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtFirstname</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtLastname</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                            <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtPassword</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createSequentialGroup</span><span class="highlight-o">(</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">140</span><span class="highlight-o">,</span> <span class="highlight-n">140</span><span class="highlight-o">,</span> <span class="highlight-n">140</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                        <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">btnSubmit</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addContainerGap</span><span class="highlight-o">(</span><span class="highlight-n">94</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">setVerticalGroup</span><span class="highlight-o">(</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createSequentialGroup</span><span class="highlight-o">(</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">14</span><span class="highlight-o">,</span> <span class="highlight-n">14</span><span class="highlight-o">,</span> <span class="highlight-n">14</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">BASELINE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel1</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtUsername</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">LEADING</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel2</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtFirstname</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">,</span> <span class="highlight-n">18</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">BASELINE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel3</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtLastname</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addPreferredGap</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">LayoutStyle</span><span class="highlight-o">.</span><span class="highlight-na">ComponentPlacement</span><span class="highlight-o">.</span><span class="highlight-na">UNRELATED</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGroup</span><span class="highlight-o">(</span><span class="highlight-n">layout</span><span class="highlight-o">.</span><span class="highlight-na">createParallelGroup</span><span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">Alignment</span><span class="highlight-o">.</span><span class="highlight-na">BASELINE</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">jLabel4</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">txtPassword</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">DEFAULT_SIZE</span><span class="highlight-o">,</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">GroupLayout</span><span class="highlight-o">.</span><span class="highlight-na">PREFERRED_SIZE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addGap</span><span class="highlight-o">(</span><span class="highlight-n">27</span><span class="highlight-o">,</span> <span class="highlight-n">27</span><span class="highlight-o">,</span> <span class="highlight-n">27</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addComponent</span><span class="highlight-o">(</span><span class="highlight-n">btnSubmit</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">.</span><span class="highlight-na">addContainerGap</span><span class="highlight-o">(</span><span class="highlight-n">100</span><span class="highlight-o">,</span> <span class="highlight-n">Short</span><span class="highlight-o">.</span><span class="highlight-na">MAX_VALUE</span><span class="highlight-o">)</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">pack</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span><span class="highlight-c1">// &lt;/editor-fold&gt;//GEN-END:initComponents
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-kt">void</span> <span class="highlight-nf">btnSubmitActionPerformed</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">awt</span><span class="highlight-o">.</span><span class="highlight-na">event</span><span class="highlight-o">.</span><span class="highlight-na">ActionEvent</span> <span class="highlight-n">evt</span><span class="highlight-o">)</span> <span class="highlight-o">{</span><span class="highlight-c1">//GEN-FIRST:event_btnSubmitActionPerformed
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-n">String</span> <span class="highlight-n">username</span> <span class="highlight-o">=</span> <span class="highlight-n">txtUsername</span><span class="highlight-o">.</span><span class="highlight-na">getText</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">String</span> <span class="highlight-n">firstname</span> <span class="highlight-o">=</span> <span class="highlight-n">txtFirstname</span><span class="highlight-o">.</span><span class="highlight-na">getText</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">String</span> <span class="highlight-n">lastname</span> <span class="highlight-o">=</span> <span class="highlight-n">txtLastname</span><span class="highlight-o">.</span><span class="highlight-na">getText</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">String</span> <span class="highlight-n">password</span> <span class="highlight-o">=</span> <span class="highlight-k">new</span> <span class="highlight-n">String</span><span class="highlight-o">(</span><span class="highlight-n">txtPassword</span><span class="highlight-o">.</span><span class="highlight-na">getPassword</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">String</span> <span class="highlight-n">registrationMessage</span> <span class="highlight-o">=</span> <span class="highlight-n">registerUser</span><span class="highlight-o">(</span><span class="highlight-n">username</span><span class="highlight-o">,</span> <span class="highlight-n">firstname</span><span class="highlight-o">,</span> <span class="highlight-n">password</span><span class="highlight-o">,</span> <span class="highlight-n">lastname</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">JOptionPane</span><span class="highlight-o">.</span><span class="highlight-na">showMessageDialog</span><span class="highlight-o">(</span><span class="highlight-n">Registration</span><span class="highlight-o">.</span><span class="highlight-na">this</span><span class="highlight-o">,</span> <span class="highlight-n">registrationMessage</span><span class="highlight-o">,</span> <span class="highlight-s">&#34;Registration Status&#34;</span><span class="highlight-o">,</span> <span class="highlight-n">JOptionPane</span><span class="highlight-o">.</span><span class="highlight-na">INFORMATION_MESSAGE</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">if</span> <span class="highlight-o">(</span><span class="highlight-n">registrationMessage</span><span class="highlight-o">.</span><span class="highlight-na">equals</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Registration successful!&#34;</span><span class="highlight-o">)</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">UserCredentials</span><span class="highlight-o">.</span><span class="highlight-na">getInstance</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">setCredentials</span><span class="highlight-o">(</span><span class="highlight-n">username</span><span class="highlight-o">,</span> <span class="highlight-n">password</span><span class="highlight-o">)</span><span class="highlight-o">;</span> <span class="highlight-c1">// Use Singleton
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>            <span class="highlight-n">dispose</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">;</span> <span class="highlight-c1">// Close registration window
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>            <span class="highlight-n">System</span><span class="highlight-o">.</span><span class="highlight-na">out</span><span class="highlight-o">.</span><span class="highlight-na">println</span><span class="highlight-o">(</span><span class="highlight-s">&#34;Stored username:&#34;</span> <span class="highlight-o">+</span> <span class="highlight-n">username</span> <span class="highlight-o">+</span><span class="highlight-s">&#34; &#34;</span><span class="highlight-o">+</span> <span class="highlight-s">&#34;Stored Pssword:&#34;</span><span class="highlight-o">+</span> <span class="highlight-n">password</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span><span class="highlight-c1">//GEN-LAST:event_btnSubmitActionPerformed
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">String</span> <span class="highlight-nf">registerUser</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">username</span><span class="highlight-o">,</span> <span class="highlight-n">String</span> <span class="highlight-n">firstname</span><span class="highlight-o">,</span> <span class="highlight-n">String</span> <span class="highlight-n">password</span><span class="highlight-o">,</span> <span class="highlight-n">String</span> <span class="highlight-n">lastname</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-c1">// Check username and password complexity
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-k">if</span> <span class="highlight-o">(</span><span class="highlight-o">!</span><span class="highlight-n">checkUserName</span><span class="highlight-o">(</span><span class="highlight-n">username</span><span class="highlight-o">)</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-k">return</span> <span class="highlight-s">&#34;Username must contain an underscore (_) and be no more than 5 characters long!&#34;</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">if</span> <span class="highlight-o">(</span><span class="highlight-o">!</span><span class="highlight-n">checkPasswordComplexity</span><span class="highlight-o">(</span><span class="highlight-n">password</span><span class="highlight-o">)</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-k">return</span> <span class="highlight-s">&#34;Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character&#34;</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-c1">// Implement actual registration logic
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-c1">// For demonstration, assume registration is successful
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-k">return</span> <span class="highlight-s">&#34;Registration successful!&#34;</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-kd">static</span> <span class="highlight-kt">boolean</span> <span class="highlight-nf">checkUserName</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">username</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">return</span> <span class="highlight-n">username</span><span class="highlight-o">.</span><span class="highlight-na">contains</span><span class="highlight-o">(</span><span class="highlight-s">&#34;_&#34;</span><span class="highlight-o">)</span> <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">username</span><span class="highlight-o">.</span><span class="highlight-na">length</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">&lt;</span><span class="highlight-o">=</span> <span class="highlight-n">5</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-kd">static</span> <span class="highlight-kt">boolean</span> <span class="highlight-nf">checkPasswordComplexity</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">password</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">return</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">length</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">&gt;</span><span class="highlight-o">=</span> <span class="highlight-n">8</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">matches</span><span class="highlight-o">(</span><span class="highlight-s">&#34;.*[A-Z].*&#34;</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">matches</span><span class="highlight-o">(</span><span class="highlight-s">&#34;.*[a-z].*&#34;</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">matches</span><span class="highlight-o">(</span><span class="highlight-s">&#34;.*\\d.*&#34;</span><span class="highlight-o">)</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">matches</span><span class="highlight-o">(</span><span class="highlight-s">&#34;.*[!@#$%^&amp;*()-_=+\\|[{]};:&#39;\&#34;,&lt;.&gt;/?`~].*&#34;</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-kt">void</span> <span class="highlight-nf">storeLoginCredentials</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">username</span><span class="highlight-o">,</span> <span class="highlight-n">String</span> <span class="highlight-n">password</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-c1">// Store login credentials
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-k">this</span><span class="highlight-o">.</span><span class="highlight-na">storedUsername</span> <span class="highlight-o">=</span> <span class="highlight-n">username</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">this</span><span class="highlight-o">.</span><span class="highlight-na">storedPassword</span> <span class="highlight-o">=</span> <span class="highlight-n">password</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-kt">boolean</span> <span class="highlight-nf">checkLoginCredentials</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">username</span><span class="highlight-o">,</span> <span class="highlight-n">String</span> <span class="highlight-n">password</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">return</span> <span class="highlight-n">username</span><span class="highlight-o">.</span><span class="highlight-na">equals</span><span class="highlight-o">(</span><span class="highlight-n">storedUsername</span><span class="highlight-o">)</span> <span class="highlight-o">&amp;</span><span class="highlight-o">&amp;</span> <span class="highlight-n">password</span><span class="highlight-o">.</span><span class="highlight-na">equals</span><span class="highlight-o">(</span><span class="highlight-n">storedPassword</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-cm">/**
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     * @param args the command line arguments
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">     */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">public</span> <span class="highlight-kd">static</span> <span class="highlight-kt">void</span> <span class="highlight-nf">main</span><span class="highlight-o">(</span><span class="highlight-n">String</span> <span class="highlight-n">args</span><span class="highlight-o">[</span><span class="highlight-o">]</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-cm">/* Set the Nimbus look and feel */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-c1">//&lt;editor-fold defaultstate=&#34;collapsed&#34; desc=&#34; Look and feel setting code (optional) &#34;&gt;
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>        <span class="highlight-cm">/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-cm">         */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-k">try</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-k">for</span> <span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">UIManager</span><span class="highlight-o">.</span><span class="highlight-na">LookAndFeelInfo</span> <span class="highlight-n">info</span> <span class="highlight-o">:</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">UIManager</span><span class="highlight-o">.</span><span class="highlight-na">getInstalledLookAndFeels</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-k">if</span> <span class="highlight-o">(</span><span class="highlight-s">&#34;Nimbus&#34;</span><span class="highlight-o">.</span><span class="highlight-na">equals</span><span class="highlight-o">(</span><span class="highlight-n">info</span><span class="highlight-o">.</span><span class="highlight-na">getName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">UIManager</span><span class="highlight-o">.</span><span class="highlight-na">setLookAndFeel</span><span class="highlight-o">(</span><span class="highlight-n">info</span><span class="highlight-o">.</span><span class="highlight-na">getClassName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                    <span class="highlight-k">break</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span> <span class="highlight-k">catch</span> <span class="highlight-o">(</span><span class="highlight-n">ClassNotFoundException</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Logger</span><span class="highlight-o">.</span><span class="highlight-na">getLogger</span><span class="highlight-o">(</span><span class="highlight-n">Registration</span><span class="highlight-o">.</span><span class="highlight-na">class</span><span class="highlight-o">.</span><span class="highlight-na">getName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">log</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Level</span><span class="highlight-o">.</span><span class="highlight-na">SEVERE</span><span class="highlight-o">,</span> <span class="highlight-kc">null</span><span class="highlight-o">,</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span> <span class="highlight-k">catch</span> <span class="highlight-o">(</span><span class="highlight-n">InstantiationException</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Logger</span><span class="highlight-o">.</span><span class="highlight-na">getLogger</span><span class="highlight-o">(</span><span class="highlight-n">Registration</span><span class="highlight-o">.</span><span class="highlight-na">class</span><span class="highlight-o">.</span><span class="highlight-na">getName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">log</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Level</span><span class="highlight-o">.</span><span class="highlight-na">SEVERE</span><span class="highlight-o">,</span> <span class="highlight-kc">null</span><span class="highlight-o">,</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span> <span class="highlight-k">catch</span> <span class="highlight-o">(</span><span class="highlight-n">IllegalAccessException</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Logger</span><span class="highlight-o">.</span><span class="highlight-na">getLogger</span><span class="highlight-o">(</span><span class="highlight-n">Registration</span><span class="highlight-o">.</span><span class="highlight-na">class</span><span class="highlight-o">.</span><span class="highlight-na">getName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">log</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Level</span><span class="highlight-o">.</span><span class="highlight-na">SEVERE</span><span class="highlight-o">,</span> <span class="highlight-kc">null</span><span class="highlight-o">,</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span> <span class="highlight-k">catch</span> <span class="highlight-o">(</span><span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">UnsupportedLookAndFeelException</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Logger</span><span class="highlight-o">.</span><span class="highlight-na">getLogger</span><span class="highlight-o">(</span><span class="highlight-n">Registration</span><span class="highlight-o">.</span><span class="highlight-na">class</span><span class="highlight-o">.</span><span class="highlight-na">getName</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">log</span><span class="highlight-o">(</span><span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">util</span><span class="highlight-o">.</span><span class="highlight-na">logging</span><span class="highlight-o">.</span><span class="highlight-na">Level</span><span class="highlight-o">.</span><span class="highlight-na">SEVERE</span><span class="highlight-o">,</span> <span class="highlight-kc">null</span><span class="highlight-o">,</span> <span class="highlight-n">ex</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-c1">//&lt;/editor-fold&gt;
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-cm">/* Create and display the form */</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-n">java</span><span class="highlight-o">.</span><span class="highlight-na">awt</span><span class="highlight-o">.</span><span class="highlight-na">EventQueue</span><span class="highlight-o">.</span><span class="highlight-na">invokeLater</span><span class="highlight-o">(</span><span class="highlight-k">new</span> <span class="highlight-n">Runnable</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-kd">public</span> <span class="highlight-kt">void</span> <span class="highlight-nf">run</span><span class="highlight-o">(</span><span class="highlight-o">)</span> <span class="highlight-o">{</span>
</span></span><span class="highlight-line"><span class="highlight-cl">                <span class="highlight-k">new</span> <span class="highlight-n">Registration</span><span class="highlight-o">(</span><span class="highlight-o">)</span><span class="highlight-o">.</span><span class="highlight-na">setVisible</span><span class="highlight-o">(</span><span class="highlight-kc">true</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">            <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">        <span class="highlight-o">}</span><span class="highlight-o">)</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-o">}</span>
</span></span><span class="highlight-line"><span class="highlight-cl">
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-c1">// Variables declaration - do not modify//GEN-BEGIN:variables
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span>    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JButton</span> <span class="highlight-n">btnSubmit</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span> <span class="highlight-n">jLabel1</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span> <span class="highlight-n">jLabel2</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span> <span class="highlight-n">jLabel3</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JLabel</span> <span class="highlight-n">jLabel4</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span> <span class="highlight-n">txtFirstname</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span> <span class="highlight-n">txtLastname</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JPasswordField</span> <span class="highlight-n">txtPassword</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-kd">private</span> <span class="highlight-n">javax</span><span class="highlight-o">.</span><span class="highlight-na">swing</span><span class="highlight-o">.</span><span class="highlight-na">JTextField</span> <span class="highlight-n">txtUsername</span><span class="highlight-o">;</span>
</span></span><span class="highlight-line"><span class="highlight-cl">    <span class="highlight-c1">// End of variables declaration//GEN-END:variables
</span></span></span><span class="highlight-line"><span class="highlight-cl"><span class="highlight-c1"></span><span class="highlight-o">}</span>
</span></span></code></pre>
                </div>
            </div>

            <div class="space"></div>
            <div class="footer">
                Powered by <a href="https://gitfront.io">GitFront</a>
            </div>
        </div>
    </body>
</html>
